spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/tamtamcatworks
      # postgreSQL
    datasource:
      url: ${DB_URL:jdbc:postgresql://localhost:5432/tamtamcatworks}
      username: ${DB_USER:postgres}
      password: ${DB_PASS:postgres}
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true